### PR TITLE
Exercise2

### PR DESCRIPTION
**Pull request by terrycheng925**
here is exercise2, hope they are ok.

### CODE REVIEW

**Comment by CorndelDevOps** [comment]
It looks like the only change was .gitignore. This likely happened because you pushed your work to `main` and only later started working off `exercise-1` branch.

I will have a look at the code already on `main`. It will be harder to get the inline comments like this, so I will write it all here.

* It looks generally very good and instructions are clear.
* Add new Environment variables to your `.env.template` to make it easy to manage - it's generally preferable to keep as much environment config in one place as possible

**Review by CorndelDevOps — APPROVED** [review]
It looks generally very good and instructions are clear.

Add new Environment variables to your `.env.template` to make it easy to manage - it's generally preferable to keep as much environment config in one place as possible

**Comment by terrycheng925** [comment]
I add the session for docker, but have some questions when run it quite gunicorn, can you please give me some direction how to run it with gunicorn.  right now it can be run with flask run.  please review my dockerfile, and appreciate if you could provide some input.

**Comment by BogRad97** [comment]
I managed to run get gunicorn running in docker, I have left suggestions with the steps I needed to take.
You will still need to:
* Update `.env.template` with the env variables that your project needs
* Create a multi-stage dockerfile, with at least a `dev` stage running flask and a `prod` stage running gunicorn
* Update the readme with instructions on how to build and run the images

**Pull request merged**
